version: '3.9'

services:
  # Python FastAPI Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-forest
    container_name: app
    volumes:
      - ./app:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
  
  # MySQL DB Service
  db:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  db_data:
    driver: local